### ISSUE TITLE
Items delete after dropping instantly

### ISSUE THREAD

**Issue by Lanthanid** [Dibeo/DDD-Dungeons-Dragons-Dimensions#1]
Exactly what the title says, i drop it and its gone, cant use the fan to mass smetl

**Comment by Dibeo** [comment]
Firstly be sure the craft is possible, second i tried what you told me and i don't have the problems, could you put a screenshot of your setup or a more precise description.

**Comment by Lanthanid** [comment]
thats the thing, it works with any item, i dropped various metals in front of a fan for smeltin, i turn around, turn back and there gone

**Comment by Lanthanid** [comment]
I reinstalled it and it fixed it for some reason so ¯\_(ツ)_/¯
